CUDA_VISIBLE_DEVICE=7 python train.py \
  --epochs 100 \
  --workers 8 \
  --device 7 \
  --batch-size 24 \
  --data data/crowdhuman.yaml \
  --img 640 640 \
  --cfg cfg/yolov7-person.yaml \
  --name body \
  --hyp data/hyp.scratch.tiny.yaml \
  --weight weights/yolov7.pt \
  --multilosses True \
  --kpt-label 0 \
  --detect-layer 'IDetectHead'
