CUDA_VISIBLE_DEVICE=7 python train.py \
  --epochs 80 \
  --workers 8 \
  --device 7 \
  --batch-size 24 \
  --data data/widerface.yaml \
  --img 640 640 \
  --cfg cfg/yolov7-person.yaml \
  --name bodyface \
  --hyp data/hyp.scratch.tiny.yaml \
  --weight runs/weights/body/weights/best.pt \
  --multilosses True \
  --kpt-label 5 \
  --detect-layer 'IKeypoint'
